version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.api
    env_file: .env
    ports:
      - "${API_PORT:-8000}:8000"
    depends_on:
      - db
      - redis
    networks:
      - domacross
    environment:
      - POSTGRES_HOST=db
  web:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.web
    env_file: .env
    ports:
      - "${WEB_PORT:-3000}:3000"
    # depends_on:
    #   - api
    networks:
      - domacross
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:${API_PORT:-8000}
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - domacross
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - domacross

volumes:
  pgdata:

networks:
  domacross:
    driver: bridge
