"""backfill verified onchain flags

Revision ID: 2754af72a70b
Revises: dd93e15ab88e
Create Date: 2025-09-04 19:59:52.820451

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2754af72a70b'
down_revision = 'dd93e15ab88e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
