"""baseline

Revision ID: 33cbbfc836fe
Revises: 
Create Date: 2025-09-06 23:44:13.665614

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '33cbbfc836fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_whitelist_active'), 'domain_whitelist', ['active'], unique=False)
    op.create_index(op.f('ix_domain_whitelist_domain_name'), 'domain_whitelist', ['domain_name'], unique=True)
    op.create_index(op.f('ix_domain_whitelist_id'), 'domain_whitelist', ['id'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tld', sa.String(length=32), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_floor_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('last_estimated_value', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('last_orderbook_snapshot_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_id'), 'domains', ['id'], unique=False)
    op.create_index(op.f('ix_domains_last_orderbook_snapshot_at'), 'domains', ['last_orderbook_snapshot_at'], unique=False)
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=True)
    op.create_index(op.f('ix_domains_tld'), 'domains', ['tld'], unique=False)
    op.create_table('governance_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_config_id'), 'governance_config', ['id'], unique=False)
    op.create_index(op.f('ix_governance_config_key'), 'governance_config', ['key'], unique=True)
    op.create_index(op.f('ix_governance_config_updated_at'), 'governance_config', ['updated_at'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('route', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_result_hash', sa.String(length=66), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_keys_created_at'), 'idempotency_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_id'), 'idempotency_keys', ['id'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=True)
    op.create_index(op.f('ix_idempotency_keys_route'), 'idempotency_keys', ['route'], unique=False)
    op.create_table('marketplace_order_cache',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('domain_contract', sa.String(length=42), nullable=True),
    sa.Column('token_id', sa.String(length=255), nullable=True),
    sa.Column('price_raw', sa.String(length=80), nullable=True),
    sa.Column('seller_wallet', sa.String(length=42), nullable=True),
    sa.Column('created_block_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_tx_hash', sa.String(length=80), nullable=True),
    sa.Column('fulfilled_block_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_marketplace_order_cache_created_at'), 'marketplace_order_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_marketplace_order_cache_created_block_time'), 'marketplace_order_cache', ['created_block_time'], unique=False)
    op.create_index(op.f('ix_marketplace_order_cache_domain_contract'), 'marketplace_order_cache', ['domain_contract'], unique=False)
    op.create_index(op.f('ix_marketplace_order_cache_fulfilled_block_time'), 'marketplace_order_cache', ['fulfilled_block_time'], unique=False)
    op.create_index(op.f('ix_marketplace_order_cache_fulfilled_tx_hash'), 'marketplace_order_cache', ['fulfilled_tx_hash'], unique=False)
    op.create_index(op.f('ix_marketplace_order_cache_order_id'), 'marketplace_order_cache', ['order_id'], unique=False)
    op.create_index(op.f('ix_marketplace_order_cache_seller_wallet'), 'marketplace_order_cache', ['seller_wallet'], unique=False)
    op.create_index(op.f('ix_marketplace_order_cache_token_id'), 'marketplace_order_cache', ['token_id'], unique=False)
    op.create_table('merkle_accumulator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('node_hash', sa.String(length=66), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merkle_accumulator_id'), 'merkle_accumulator', ['id'], unique=False)
    op.create_index(op.f('ix_merkle_accumulator_level'), 'merkle_accumulator', ['level'], unique=True)
    op.create_index(op.f('ix_merkle_accumulator_updated_at'), 'merkle_accumulator', ['updated_at'], unique=False)
    op.create_table('merkle_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_event_id', sa.Integer(), nullable=False),
    sa.Column('merkle_root', sa.String(length=66), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('signature', sa.String(length=512), nullable=True),
    sa.Column('anchor_tx_hash', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merkle_snapshots_anchor_tx_hash'), 'merkle_snapshots', ['anchor_tx_hash'], unique=False)
    op.create_index(op.f('ix_merkle_snapshots_created_at'), 'merkle_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_merkle_snapshots_id'), 'merkle_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_merkle_snapshots_last_event_id'), 'merkle_snapshots', ['last_event_id'], unique=False)
    op.create_index(op.f('ix_merkle_snapshots_merkle_root'), 'merkle_snapshots', ['merkle_root'], unique=False)
    op.create_table('poll_ingest_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_ack_event_id', sa.Integer(), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_integrity_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_ingest_state_id'), 'poll_ingest_state', ['id'], unique=False)
    op.create_index(op.f('ix_poll_ingest_state_last_ack_event_id'), 'poll_ingest_state', ['last_ack_event_id'], unique=False)
    op.create_index(op.f('ix_poll_ingest_state_last_ingested_at'), 'poll_ingest_state', ['last_ingested_at'], unique=False)
    op.create_table('processed_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id', name='uq_processed_events_unique')
    )
    op.create_index(op.f('ix_processed_events_event_type'), 'processed_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_processed_events_id'), 'processed_events', ['id'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_id'), 'seasons', ['id'], unique=False)
    op.create_index(op.f('ix_seasons_name'), 'seasons', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('kyc_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    op.create_index(op.f('ix_users_kyc_verified'), 'users', ['kyc_verified'], unique=False)
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    op.create_table('admin_action_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_action_audit_action_type'), 'admin_action_audit', ['action_type'], unique=False)
    op.create_index(op.f('ix_admin_action_audit_admin_user_id'), 'admin_action_audit', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_action_audit_created_at'), 'admin_action_audit', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_action_audit_id'), 'admin_action_audit', ['id'], unique=False)
    op.create_index(op.f('ix_admin_action_audit_target'), 'admin_action_audit', ['target'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('integrity_hash', sa.String(length=130), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_integrity_hash'), 'audit_events', ['integrity_hash'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_address', sa.String(length=42), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_fee', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('prize_pool_usdc', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('last_status_transition_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitions_contract_address'), 'competitions', ['contract_address'], unique=True)
    op.create_index(op.f('ix_competitions_id'), 'competitions', ['id'], unique=False)
    op.create_index(op.f('ix_competitions_last_status_transition_at'), 'competitions', ['last_status_transition_at'], unique=False)
    op.create_index(op.f('ix_competitions_season_id'), 'competitions', ['season_id'], unique=False)
    op.create_index(op.f('ix_competitions_status'), 'competitions', ['status'], unique=False)
    op.create_table('domain_basket_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onchain_basket_id', sa.String(length=64), nullable=True),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.Column('domain_names', sa.JSON(), nullable=False),
    sa.Column('weights_bps', sa.JSON(), nullable=False),
    sa.Column('token_uri', sa.String(length=512), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('redeemed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_basket_records_created_at'), 'domain_basket_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_basket_records_creator_user_id'), 'domain_basket_records', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_domain_basket_records_id'), 'domain_basket_records', ['id'], unique=False)
    op.create_index(op.f('ix_domain_basket_records_onchain_basket_id'), 'domain_basket_records', ['onchain_basket_id'], unique=False)
    op.create_index(op.f('ix_domain_basket_records_redeemed'), 'domain_basket_records', ['redeemed'], unique=False)
    op.create_index(op.f('ix_domain_basket_records_redeemed_at'), 'domain_basket_records', ['redeemed_at'], unique=False)
    op.create_table('domain_valuation_disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_valuation_disputes_created_at'), 'domain_valuation_disputes', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_valuation_disputes_created_by_user_id'), 'domain_valuation_disputes', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_domain_valuation_disputes_domain_name'), 'domain_valuation_disputes', ['domain_name'], unique=False)
    op.create_index(op.f('ix_domain_valuation_disputes_id'), 'domain_valuation_disputes', ['id'], unique=False)
    op.create_index(op.f('ix_domain_valuation_disputes_resolved_at'), 'domain_valuation_disputes', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_domain_valuation_disputes_status'), 'domain_valuation_disputes', ['status'], unique=False)
    op.create_table('domain_valuation_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('override_value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_name', name='uq_domain_override_domain')
    )
    op.create_index(op.f('ix_domain_valuation_overrides_created_at'), 'domain_valuation_overrides', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_valuation_overrides_created_by_user_id'), 'domain_valuation_overrides', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_domain_valuation_overrides_domain_name'), 'domain_valuation_overrides', ['domain_name'], unique=False)
    op.create_index(op.f('ix_domain_valuation_overrides_expires_at'), 'domain_valuation_overrides', ['expires_at'], unique=False)
    op.create_index(op.f('ix_domain_valuation_overrides_id'), 'domain_valuation_overrides', ['id'], unique=False)
    op.create_table('governance_config_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_config_audit_admin_user_id'), 'governance_config_audit', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_governance_config_audit_created_at'), 'governance_config_audit', ['created_at'], unique=False)
    op.create_index(op.f('ix_governance_config_audit_id'), 'governance_config_audit', ['id'], unique=False)
    op.create_index(op.f('ix_governance_config_audit_key'), 'governance_config_audit', ['key'], unique=False)
    op.create_table('governance_config_pending',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('new_value', sa.JSON(), nullable=False),
    sa.Column('activate_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'activate_at', name='uq_governance_pending_key_time')
    )
    op.create_index(op.f('ix_governance_config_pending_activate_at'), 'governance_config_pending', ['activate_at'], unique=False)
    op.create_index(op.f('ix_governance_config_pending_applied'), 'governance_config_pending', ['applied'], unique=False)
    op.create_index(op.f('ix_governance_config_pending_created_at'), 'governance_config_pending', ['created_at'], unique=False)
    op.create_index(op.f('ix_governance_config_pending_id'), 'governance_config_pending', ['id'], unique=False)
    op.create_index(op.f('ix_governance_config_pending_key'), 'governance_config_pending', ['key'], unique=False)
    op.create_index(op.f('ix_governance_config_pending_requested_by_user_id'), 'governance_config_pending', ['requested_by_user_id'], unique=False)
    op.create_table('kyc_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('document_hash', sa.String(length=130), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_requests_created_at'), 'kyc_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_kyc_requests_id'), 'kyc_requests', ['id'], unique=False)
    op.create_index(op.f('ix_kyc_requests_reviewed_at'), 'kyc_requests', ['reviewed_at'], unique=False)
    op.create_index(op.f('ix_kyc_requests_status'), 'kyc_requests', ['status'], unique=False)
    op.create_index(op.f('ix_kyc_requests_user_id'), 'kyc_requests', ['user_id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('seller_wallet', sa.String(length=42), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('external_order_id', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_index(op.f('ix_listings_active'), 'listings', ['active'], unique=False)
    op.create_index(op.f('ix_listings_domain_name'), 'listings', ['domain_name'], unique=False)
    op.create_index(op.f('ix_listings_expires_at'), 'listings', ['expires_at'], unique=False)
    op.create_index(op.f('ix_listings_external_order_id'), 'listings', ['external_order_id'], unique=True)
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    op.create_index(op.f('ix_listings_seller_wallet'), 'listings', ['seller_wallet'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('buyer_wallet', sa.String(length=42), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('external_order_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_index(op.f('ix_offers_active'), 'offers', ['active'], unique=False)
    op.create_index(op.f('ix_offers_buyer_wallet'), 'offers', ['buyer_wallet'], unique=False)
    op.create_index(op.f('ix_offers_domain_name'), 'offers', ['domain_name'], unique=False)
    op.create_index(op.f('ix_offers_external_order_id'), 'offers', ['external_order_id'], unique=True)
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_table('orderbook_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('size', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderbook_snapshots_collected_at'), 'orderbook_snapshots', ['collected_at'], unique=False)
    op.create_index(op.f('ix_orderbook_snapshots_domain_name'), 'orderbook_snapshots', ['domain_name'], unique=False)
    op.create_index(op.f('ix_orderbook_snapshots_id'), 'orderbook_snapshots', ['id'], unique=False)
    op.create_table('valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuations_created_at'), 'valuations', ['created_at'], unique=False)
    op.create_index(op.f('ix_valuations_domain_name'), 'valuations', ['domain_name'], unique=False)
    op.create_index(op.f('ix_valuations_id'), 'valuations', ['id'], unique=False)
    op.create_table('basket_tokenization_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basket_record_id', sa.Integer(), nullable=False),
    sa.Column('onchain_token_contract', sa.String(length=42), nullable=True),
    sa.Column('onchain_token_id', sa.String(length=128), nullable=True),
    sa.Column('minted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nav_at_mint', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['basket_record_id'], ['domain_basket_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basket_tokenization_records_active'), 'basket_tokenization_records', ['active'], unique=False)
    op.create_index(op.f('ix_basket_tokenization_records_basket_record_id'), 'basket_tokenization_records', ['basket_record_id'], unique=False)
    op.create_index(op.f('ix_basket_tokenization_records_created_at'), 'basket_tokenization_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_basket_tokenization_records_id'), 'basket_tokenization_records', ['id'], unique=False)
    op.create_index(op.f('ix_basket_tokenization_records_minted_at'), 'basket_tokenization_records', ['minted_at'], unique=False)
    op.create_index(op.f('ix_basket_tokenization_records_onchain_token_contract'), 'basket_tokenization_records', ['onchain_token_contract'], unique=False)
    op.create_index(op.f('ix_basket_tokenization_records_onchain_token_id'), 'basket_tokenization_records', ['onchain_token_id'], unique=False)
    op.create_table('competition_epochs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('epoch_index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reward_pool', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('distributed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'epoch_index', name='uq_competition_epoch_idx')
    )
    op.create_index(op.f('ix_competition_epochs_competition_id'), 'competition_epochs', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_epochs_distributed'), 'competition_epochs', ['distributed'], unique=False)
    op.create_index(op.f('ix_competition_epochs_id'), 'competition_epochs', ['id'], unique=False)
    op.create_table('competition_escrow_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_usdc', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('deposited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('refunded', sa.Boolean(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'user_id', name='uq_competition_user_escrow')
    )
    op.create_index(op.f('ix_competition_escrow_balances_competition_id'), 'competition_escrow_balances', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_escrow_balances_deposited_at'), 'competition_escrow_balances', ['deposited_at'], unique=False)
    op.create_index(op.f('ix_competition_escrow_balances_id'), 'competition_escrow_balances', ['id'], unique=False)
    op.create_index(op.f('ix_competition_escrow_balances_refunded'), 'competition_escrow_balances', ['refunded'], unique=False)
    op.create_index(op.f('ix_competition_escrow_balances_refunded_at'), 'competition_escrow_balances', ['refunded_at'], unique=False)
    op.create_index(op.f('ix_competition_escrow_balances_user_id'), 'competition_escrow_balances', ['user_id'], unique=False)
    op.create_table('domain_etfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_shares', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('nav_last', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('nav_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creation_unit_size', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('management_fee_bps', sa.Integer(), nullable=True),
    sa.Column('performance_fee_bps', sa.Integer(), nullable=True),
    sa.Column('fee_accrued', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('nav_high_water', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('management_fee_last_accrued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creation_fee_bps', sa.Integer(), nullable=True),
    sa.Column('redemption_fee_bps', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', name='uq_domain_etf_symbol')
    )
    op.create_index(op.f('ix_domain_etfs_competition_id'), 'domain_etfs', ['competition_id'], unique=False)
    op.create_index(op.f('ix_domain_etfs_id'), 'domain_etfs', ['id'], unique=False)
    op.create_index(op.f('ix_domain_etfs_management_fee_last_accrued_at'), 'domain_etfs', ['management_fee_last_accrued_at'], unique=False)
    op.create_index(op.f('ix_domain_etfs_owner_user_id'), 'domain_etfs', ['owner_user_id'], unique=False)
    op.create_table('incentive_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('epoch_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('base_emission_per_epoch', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('weight_volume_bps', sa.Integer(), nullable=False),
    sa.Column('weight_pnl_bps', sa.Integer(), nullable=False),
    sa.Column('weight_turnover_bps', sa.Integer(), nullable=False),
    sa.Column('weight_concentration_bps', sa.Integer(), nullable=False),
    sa.Column('bonus_early_join_bps', sa.Integer(), nullable=False),
    sa.Column('min_participants_full_emission', sa.Integer(), nullable=False),
    sa.Column('emission_reduction_factor_bps', sa.Integer(), nullable=False),
    sa.Column('volume_tier_thresholds', sa.JSON(), nullable=True),
    sa.Column('holding_duration_tiers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incentive_schedules_competition_id'), 'incentive_schedules', ['competition_id'], unique=False)
    op.create_index(op.f('ix_incentive_schedules_created_at'), 'incentive_schedules', ['created_at'], unique=False)
    op.create_index(op.f('ix_incentive_schedules_id'), 'incentive_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_incentive_schedules_name'), 'incentive_schedules', ['name'], unique=True)
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_table('competition_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('epoch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('sharpe_like', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('turnover_ratio', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('concentration_index', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('raw_reward_amount', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('reward_amount', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('distributed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['epoch_id'], ['competition_epochs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('epoch_id', 'user_id', name='uq_epoch_user_reward')
    )
    op.create_index(op.f('ix_competition_rewards_claimed_at'), 'competition_rewards', ['claimed_at'], unique=False)
    op.create_index(op.f('ix_competition_rewards_competition_id'), 'competition_rewards', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_rewards_distributed_at'), 'competition_rewards', ['distributed_at'], unique=False)
    op.create_index(op.f('ix_competition_rewards_epoch_id'), 'competition_rewards', ['epoch_id'], unique=False)
    op.create_index(op.f('ix_competition_rewards_id'), 'competition_rewards', ['id'], unique=False)
    op.create_index(op.f('ix_competition_rewards_user_id'), 'competition_rewards', ['user_id'], unique=False)
    op.create_table('domain_etf_fee_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('nav_per_share_snapshot', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['etf_id'], ['domain_etfs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_etf_fee_events_created_at'), 'domain_etf_fee_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_etf_fee_events_etf_id'), 'domain_etf_fee_events', ['etf_id'], unique=False)
    op.create_index(op.f('ix_domain_etf_fee_events_event_type'), 'domain_etf_fee_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_domain_etf_fee_events_id'), 'domain_etf_fee_events', ['id'], unique=False)
    op.create_table('domain_etf_nav_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nav_per_share', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['etf_id'], ['domain_etfs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_etf_nav_history_etf_id'), 'domain_etf_nav_history', ['etf_id'], unique=False)
    op.create_index(op.f('ix_domain_etf_nav_history_id'), 'domain_etf_nav_history', ['id'], unique=False)
    op.create_index(op.f('ix_domain_etf_nav_history_snapshot_time'), 'domain_etf_nav_history', ['snapshot_time'], unique=False)
    op.create_table('domain_etf_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('weight_bps', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.ForeignKeyConstraint(['etf_id'], ['domain_etfs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etf_id', 'domain_name', name='uq_domain_etf_domain')
    )
    op.create_index(op.f('ix_domain_etf_positions_domain_name'), 'domain_etf_positions', ['domain_name'], unique=False)
    op.create_index(op.f('ix_domain_etf_positions_etf_id'), 'domain_etf_positions', ['etf_id'], unique=False)
    op.create_index(op.f('ix_domain_etf_positions_id'), 'domain_etf_positions', ['id'], unique=False)
    op.create_table('domain_etf_redemption_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('nav_per_share_snapshot', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_onchain', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['etf_id'], ['domain_etfs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_etf_redemption_intents_created_at'), 'domain_etf_redemption_intents', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_etf_redemption_intents_etf_id'), 'domain_etf_redemption_intents', ['etf_id'], unique=False)
    op.create_index(op.f('ix_domain_etf_redemption_intents_executed_at'), 'domain_etf_redemption_intents', ['executed_at'], unique=False)
    op.create_index(op.f('ix_domain_etf_redemption_intents_id'), 'domain_etf_redemption_intents', ['id'], unique=False)
    op.create_index(op.f('ix_domain_etf_redemption_intents_user_id'), 'domain_etf_redemption_intents', ['user_id'], unique=False)
    op.create_index(op.f('ix_domain_etf_redemption_intents_verified_onchain'), 'domain_etf_redemption_intents', ['verified_onchain'], unique=False)
    op.create_table('domain_etf_share_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flow_type', sa.String(length=8), nullable=False),
    sa.Column('shares', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('cash_value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('nav_per_share', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('settlement_order_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['etf_id'], ['domain_etfs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_etf_share_flows_created_at'), 'domain_etf_share_flows', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_etf_share_flows_etf_id'), 'domain_etf_share_flows', ['etf_id'], unique=False)
    op.create_index(op.f('ix_domain_etf_share_flows_id'), 'domain_etf_share_flows', ['id'], unique=False)
    op.create_index(op.f('ix_domain_etf_share_flows_user_id'), 'domain_etf_share_flows', ['user_id'], unique=False)
    op.create_table('domain_etf_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('lock_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['etf_id'], ['domain_etfs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etf_id', 'user_id', name='uq_domain_etf_share_holder')
    )
    op.create_index(op.f('ix_domain_etf_shares_etf_id'), 'domain_etf_shares', ['etf_id'], unique=False)
    op.create_index(op.f('ix_domain_etf_shares_id'), 'domain_etf_shares', ['id'], unique=False)
    op.create_index(op.f('ix_domain_etf_shares_lock_until'), 'domain_etf_shares', ['lock_until'], unique=False)
    op.create_index(op.f('ix_domain_etf_shares_user_id'), 'domain_etf_shares', ['user_id'], unique=False)
    op.create_table('incentive_epochs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('epoch_index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_emission', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('actual_emission', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('participation_count', sa.Integer(), nullable=True),
    sa.Column('adjusted', sa.Boolean(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['incentive_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'epoch_index', name='uq_incentive_schedule_epoch')
    )
    op.create_index(op.f('ix_incentive_epochs_adjusted'), 'incentive_epochs', ['adjusted'], unique=False)
    op.create_index(op.f('ix_incentive_epochs_created_at'), 'incentive_epochs', ['created_at'], unique=False)
    op.create_index(op.f('ix_incentive_epochs_end_time'), 'incentive_epochs', ['end_time'], unique=False)
    op.create_index(op.f('ix_incentive_epochs_finalized_at'), 'incentive_epochs', ['finalized_at'], unique=False)
    op.create_index(op.f('ix_incentive_epochs_id'), 'incentive_epochs', ['id'], unique=False)
    op.create_index(op.f('ix_incentive_epochs_schedule_id'), 'incentive_epochs', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_incentive_epochs_start_time'), 'incentive_epochs', ['start_time'], unique=False)
    op.create_table('participant_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'domain_name', name='uq_participant_domain_holding')
    )
    op.create_index(op.f('ix_participant_holdings_domain_name'), 'participant_holdings', ['domain_name'], unique=False)
    op.create_index(op.f('ix_participant_holdings_id'), 'participant_holdings', ['id'], unique=False)
    op.create_index(op.f('ix_participant_holdings_participant_id'), 'participant_holdings', ['participant_id'], unique=False)
    op.create_index(op.f('ix_participant_holdings_updated_at'), 'participant_holdings', ['updated_at'], unique=False)
    op.create_table('portfolio_value_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_value_history_id'), 'portfolio_value_history', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_value_history_participant_id'), 'portfolio_value_history', ['participant_id'], unique=False)
    op.create_index(op.f('ix_portfolio_value_history_snapshot_time'), 'portfolio_value_history', ['snapshot_time'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('domain_token_address', sa.String(length=42), nullable=False),
    sa.Column('domain_token_id', sa.String(length=255), nullable=False),
    sa.Column('trade_type', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_tx_hash'), 'trades', ['tx_hash'], unique=False)
    op.create_table('domain_etf_revenue_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('fee_event_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['etf_id'], ['domain_etfs.id'], ),
    sa.ForeignKeyConstraint(['fee_event_id'], ['domain_etf_fee_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_etf_revenue_shares_created_at'), 'domain_etf_revenue_shares', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_etf_revenue_shares_etf_id'), 'domain_etf_revenue_shares', ['etf_id'], unique=False)
    op.create_index(op.f('ix_domain_etf_revenue_shares_fee_event_id'), 'domain_etf_revenue_shares', ['fee_event_id'], unique=False)
    op.create_index(op.f('ix_domain_etf_revenue_shares_id'), 'domain_etf_revenue_shares', ['id'], unique=False)
    op.create_index(op.f('ix_domain_etf_revenue_shares_user_id'), 'domain_etf_revenue_shares', ['user_id'], unique=False)
    op.create_table('incentive_user_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('epoch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('turnover_ratio', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('concentration_index', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('base_points', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('bonus_points', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('total_points', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('reward_amount', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('distributed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['epoch_id'], ['incentive_epochs.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['incentive_schedules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('epoch_id', 'user_id', name='uq_incentive_epoch_user')
    )
    op.create_index(op.f('ix_incentive_user_points_created_at'), 'incentive_user_points', ['created_at'], unique=False)
    op.create_index(op.f('ix_incentive_user_points_distributed_at'), 'incentive_user_points', ['distributed_at'], unique=False)
    op.create_index(op.f('ix_incentive_user_points_epoch_id'), 'incentive_user_points', ['epoch_id'], unique=False)
    op.create_index(op.f('ix_incentive_user_points_id'), 'incentive_user_points', ['id'], unique=False)
    op.create_index(op.f('ix_incentive_user_points_schedule_id'), 'incentive_user_points', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_incentive_user_points_user_id'), 'incentive_user_points', ['user_id'], unique=False)
    op.create_table('trade_risk_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_risk_flags_created_at'), 'trade_risk_flags', ['created_at'], unique=False)
    op.create_index(op.f('ix_trade_risk_flags_flag_type'), 'trade_risk_flags', ['flag_type'], unique=False)
    op.create_index(op.f('ix_trade_risk_flags_id'), 'trade_risk_flags', ['id'], unique=False)
    op.create_index(op.f('ix_trade_risk_flags_trade_id'), 'trade_risk_flags', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_risk_flags_trade_id'), table_name='trade_risk_flags')
    op.drop_index(op.f('ix_trade_risk_flags_id'), table_name='trade_risk_flags')
    op.drop_index(op.f('ix_trade_risk_flags_flag_type'), table_name='trade_risk_flags')
    op.drop_index(op.f('ix_trade_risk_flags_created_at'), table_name='trade_risk_flags')
    op.drop_table('trade_risk_flags')
    op.drop_index(op.f('ix_incentive_user_points_user_id'), table_name='incentive_user_points')
    op.drop_index(op.f('ix_incentive_user_points_schedule_id'), table_name='incentive_user_points')
    op.drop_index(op.f('ix_incentive_user_points_id'), table_name='incentive_user_points')
    op.drop_index(op.f('ix_incentive_user_points_epoch_id'), table_name='incentive_user_points')
    op.drop_index(op.f('ix_incentive_user_points_distributed_at'), table_name='incentive_user_points')
    op.drop_index(op.f('ix_incentive_user_points_created_at'), table_name='incentive_user_points')
    op.drop_table('incentive_user_points')
    op.drop_index(op.f('ix_domain_etf_revenue_shares_user_id'), table_name='domain_etf_revenue_shares')
    op.drop_index(op.f('ix_domain_etf_revenue_shares_id'), table_name='domain_etf_revenue_shares')
    op.drop_index(op.f('ix_domain_etf_revenue_shares_fee_event_id'), table_name='domain_etf_revenue_shares')
    op.drop_index(op.f('ix_domain_etf_revenue_shares_etf_id'), table_name='domain_etf_revenue_shares')
    op.drop_index(op.f('ix_domain_etf_revenue_shares_created_at'), table_name='domain_etf_revenue_shares')
    op.drop_table('domain_etf_revenue_shares')
    op.drop_index(op.f('ix_trades_tx_hash'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_portfolio_value_history_snapshot_time'), table_name='portfolio_value_history')
    op.drop_index(op.f('ix_portfolio_value_history_participant_id'), table_name='portfolio_value_history')
    op.drop_index(op.f('ix_portfolio_value_history_id'), table_name='portfolio_value_history')
    op.drop_table('portfolio_value_history')
    op.drop_index(op.f('ix_participant_holdings_updated_at'), table_name='participant_holdings')
    op.drop_index(op.f('ix_participant_holdings_participant_id'), table_name='participant_holdings')
    op.drop_index(op.f('ix_participant_holdings_id'), table_name='participant_holdings')
    op.drop_index(op.f('ix_participant_holdings_domain_name'), table_name='participant_holdings')
    op.drop_table('participant_holdings')
    op.drop_index(op.f('ix_incentive_epochs_start_time'), table_name='incentive_epochs')
    op.drop_index(op.f('ix_incentive_epochs_schedule_id'), table_name='incentive_epochs')
    op.drop_index(op.f('ix_incentive_epochs_id'), table_name='incentive_epochs')
    op.drop_index(op.f('ix_incentive_epochs_finalized_at'), table_name='incentive_epochs')
    op.drop_index(op.f('ix_incentive_epochs_end_time'), table_name='incentive_epochs')
    op.drop_index(op.f('ix_incentive_epochs_created_at'), table_name='incentive_epochs')
    op.drop_index(op.f('ix_incentive_epochs_adjusted'), table_name='incentive_epochs')
    op.drop_table('incentive_epochs')
    op.drop_index(op.f('ix_domain_etf_shares_user_id'), table_name='domain_etf_shares')
    op.drop_index(op.f('ix_domain_etf_shares_lock_until'), table_name='domain_etf_shares')
    op.drop_index(op.f('ix_domain_etf_shares_id'), table_name='domain_etf_shares')
    op.drop_index(op.f('ix_domain_etf_shares_etf_id'), table_name='domain_etf_shares')
    op.drop_table('domain_etf_shares')
    op.drop_index(op.f('ix_domain_etf_share_flows_user_id'), table_name='domain_etf_share_flows')
    op.drop_index(op.f('ix_domain_etf_share_flows_id'), table_name='domain_etf_share_flows')
    op.drop_index(op.f('ix_domain_etf_share_flows_etf_id'), table_name='domain_etf_share_flows')
    op.drop_index(op.f('ix_domain_etf_share_flows_created_at'), table_name='domain_etf_share_flows')
    op.drop_table('domain_etf_share_flows')
    op.drop_index(op.f('ix_domain_etf_redemption_intents_verified_onchain'), table_name='domain_etf_redemption_intents')
    op.drop_index(op.f('ix_domain_etf_redemption_intents_user_id'), table_name='domain_etf_redemption_intents')
    op.drop_index(op.f('ix_domain_etf_redemption_intents_id'), table_name='domain_etf_redemption_intents')
    op.drop_index(op.f('ix_domain_etf_redemption_intents_executed_at'), table_name='domain_etf_redemption_intents')
    op.drop_index(op.f('ix_domain_etf_redemption_intents_etf_id'), table_name='domain_etf_redemption_intents')
    op.drop_index(op.f('ix_domain_etf_redemption_intents_created_at'), table_name='domain_etf_redemption_intents')
    op.drop_table('domain_etf_redemption_intents')
    op.drop_index(op.f('ix_domain_etf_positions_id'), table_name='domain_etf_positions')
    op.drop_index(op.f('ix_domain_etf_positions_etf_id'), table_name='domain_etf_positions')
    op.drop_index(op.f('ix_domain_etf_positions_domain_name'), table_name='domain_etf_positions')
    op.drop_table('domain_etf_positions')
    op.drop_index(op.f('ix_domain_etf_nav_history_snapshot_time'), table_name='domain_etf_nav_history')
    op.drop_index(op.f('ix_domain_etf_nav_history_id'), table_name='domain_etf_nav_history')
    op.drop_index(op.f('ix_domain_etf_nav_history_etf_id'), table_name='domain_etf_nav_history')
    op.drop_table('domain_etf_nav_history')
    op.drop_index(op.f('ix_domain_etf_fee_events_id'), table_name='domain_etf_fee_events')
    op.drop_index(op.f('ix_domain_etf_fee_events_event_type'), table_name='domain_etf_fee_events')
    op.drop_index(op.f('ix_domain_etf_fee_events_etf_id'), table_name='domain_etf_fee_events')
    op.drop_index(op.f('ix_domain_etf_fee_events_created_at'), table_name='domain_etf_fee_events')
    op.drop_table('domain_etf_fee_events')
    op.drop_index(op.f('ix_competition_rewards_user_id'), table_name='competition_rewards')
    op.drop_index(op.f('ix_competition_rewards_id'), table_name='competition_rewards')
    op.drop_index(op.f('ix_competition_rewards_epoch_id'), table_name='competition_rewards')
    op.drop_index(op.f('ix_competition_rewards_distributed_at'), table_name='competition_rewards')
    op.drop_index(op.f('ix_competition_rewards_competition_id'), table_name='competition_rewards')
    op.drop_index(op.f('ix_competition_rewards_claimed_at'), table_name='competition_rewards')
    op.drop_table('competition_rewards')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_incentive_schedules_name'), table_name='incentive_schedules')
    op.drop_index(op.f('ix_incentive_schedules_id'), table_name='incentive_schedules')
    op.drop_index(op.f('ix_incentive_schedules_created_at'), table_name='incentive_schedules')
    op.drop_index(op.f('ix_incentive_schedules_competition_id'), table_name='incentive_schedules')
    op.drop_table('incentive_schedules')
    op.drop_index(op.f('ix_domain_etfs_owner_user_id'), table_name='domain_etfs')
    op.drop_index(op.f('ix_domain_etfs_management_fee_last_accrued_at'), table_name='domain_etfs')
    op.drop_index(op.f('ix_domain_etfs_id'), table_name='domain_etfs')
    op.drop_index(op.f('ix_domain_etfs_competition_id'), table_name='domain_etfs')
    op.drop_table('domain_etfs')
    op.drop_index(op.f('ix_competition_escrow_balances_user_id'), table_name='competition_escrow_balances')
    op.drop_index(op.f('ix_competition_escrow_balances_refunded_at'), table_name='competition_escrow_balances')
    op.drop_index(op.f('ix_competition_escrow_balances_refunded'), table_name='competition_escrow_balances')
    op.drop_index(op.f('ix_competition_escrow_balances_id'), table_name='competition_escrow_balances')
    op.drop_index(op.f('ix_competition_escrow_balances_deposited_at'), table_name='competition_escrow_balances')
    op.drop_index(op.f('ix_competition_escrow_balances_competition_id'), table_name='competition_escrow_balances')
    op.drop_table('competition_escrow_balances')
    op.drop_index(op.f('ix_competition_epochs_id'), table_name='competition_epochs')
    op.drop_index(op.f('ix_competition_epochs_distributed'), table_name='competition_epochs')
    op.drop_index(op.f('ix_competition_epochs_competition_id'), table_name='competition_epochs')
    op.drop_table('competition_epochs')
    op.drop_index(op.f('ix_basket_tokenization_records_onchain_token_id'), table_name='basket_tokenization_records')
    op.drop_index(op.f('ix_basket_tokenization_records_onchain_token_contract'), table_name='basket_tokenization_records')
    op.drop_index(op.f('ix_basket_tokenization_records_minted_at'), table_name='basket_tokenization_records')
    op.drop_index(op.f('ix_basket_tokenization_records_id'), table_name='basket_tokenization_records')
    op.drop_index(op.f('ix_basket_tokenization_records_created_at'), table_name='basket_tokenization_records')
    op.drop_index(op.f('ix_basket_tokenization_records_basket_record_id'), table_name='basket_tokenization_records')
    op.drop_index(op.f('ix_basket_tokenization_records_active'), table_name='basket_tokenization_records')
    op.drop_table('basket_tokenization_records')
    op.drop_index(op.f('ix_valuations_id'), table_name='valuations')
    op.drop_index(op.f('ix_valuations_domain_name'), table_name='valuations')
    op.drop_index(op.f('ix_valuations_created_at'), table_name='valuations')
    op.drop_table('valuations')
    op.drop_index(op.f('ix_orderbook_snapshots_id'), table_name='orderbook_snapshots')
    op.drop_index(op.f('ix_orderbook_snapshots_domain_name'), table_name='orderbook_snapshots')
    op.drop_index(op.f('ix_orderbook_snapshots_collected_at'), table_name='orderbook_snapshots')
    op.drop_table('orderbook_snapshots')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_external_order_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_domain_name'), table_name='offers')
    op.drop_index(op.f('ix_offers_buyer_wallet'), table_name='offers')
    op.drop_index(op.f('ix_offers_active'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_listings_seller_wallet'), table_name='listings')
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_external_order_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_expires_at'), table_name='listings')
    op.drop_index(op.f('ix_listings_domain_name'), table_name='listings')
    op.drop_index(op.f('ix_listings_active'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_kyc_requests_user_id'), table_name='kyc_requests')
    op.drop_index(op.f('ix_kyc_requests_status'), table_name='kyc_requests')
    op.drop_index(op.f('ix_kyc_requests_reviewed_at'), table_name='kyc_requests')
    op.drop_index(op.f('ix_kyc_requests_id'), table_name='kyc_requests')
    op.drop_index(op.f('ix_kyc_requests_created_at'), table_name='kyc_requests')
    op.drop_table('kyc_requests')
    op.drop_index(op.f('ix_governance_config_pending_requested_by_user_id'), table_name='governance_config_pending')
    op.drop_index(op.f('ix_governance_config_pending_key'), table_name='governance_config_pending')
    op.drop_index(op.f('ix_governance_config_pending_id'), table_name='governance_config_pending')
    op.drop_index(op.f('ix_governance_config_pending_created_at'), table_name='governance_config_pending')
    op.drop_index(op.f('ix_governance_config_pending_applied'), table_name='governance_config_pending')
    op.drop_index(op.f('ix_governance_config_pending_activate_at'), table_name='governance_config_pending')
    op.drop_table('governance_config_pending')
    op.drop_index(op.f('ix_governance_config_audit_key'), table_name='governance_config_audit')
    op.drop_index(op.f('ix_governance_config_audit_id'), table_name='governance_config_audit')
    op.drop_index(op.f('ix_governance_config_audit_created_at'), table_name='governance_config_audit')
    op.drop_index(op.f('ix_governance_config_audit_admin_user_id'), table_name='governance_config_audit')
    op.drop_table('governance_config_audit')
    op.drop_index(op.f('ix_domain_valuation_overrides_id'), table_name='domain_valuation_overrides')
    op.drop_index(op.f('ix_domain_valuation_overrides_expires_at'), table_name='domain_valuation_overrides')
    op.drop_index(op.f('ix_domain_valuation_overrides_domain_name'), table_name='domain_valuation_overrides')
    op.drop_index(op.f('ix_domain_valuation_overrides_created_by_user_id'), table_name='domain_valuation_overrides')
    op.drop_index(op.f('ix_domain_valuation_overrides_created_at'), table_name='domain_valuation_overrides')
    op.drop_table('domain_valuation_overrides')
    op.drop_index(op.f('ix_domain_valuation_disputes_status'), table_name='domain_valuation_disputes')
    op.drop_index(op.f('ix_domain_valuation_disputes_resolved_at'), table_name='domain_valuation_disputes')
    op.drop_index(op.f('ix_domain_valuation_disputes_id'), table_name='domain_valuation_disputes')
    op.drop_index(op.f('ix_domain_valuation_disputes_domain_name'), table_name='domain_valuation_disputes')
    op.drop_index(op.f('ix_domain_valuation_disputes_created_by_user_id'), table_name='domain_valuation_disputes')
    op.drop_index(op.f('ix_domain_valuation_disputes_created_at'), table_name='domain_valuation_disputes')
    op.drop_table('domain_valuation_disputes')
    op.drop_index(op.f('ix_domain_basket_records_redeemed_at'), table_name='domain_basket_records')
    op.drop_index(op.f('ix_domain_basket_records_redeemed'), table_name='domain_basket_records')
    op.drop_index(op.f('ix_domain_basket_records_onchain_basket_id'), table_name='domain_basket_records')
    op.drop_index(op.f('ix_domain_basket_records_id'), table_name='domain_basket_records')
    op.drop_index(op.f('ix_domain_basket_records_creator_user_id'), table_name='domain_basket_records')
    op.drop_index(op.f('ix_domain_basket_records_created_at'), table_name='domain_basket_records')
    op.drop_table('domain_basket_records')
    op.drop_index(op.f('ix_competitions_status'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_season_id'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_last_status_transition_at'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_id'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_contract_address'), table_name='competitions')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_integrity_hash'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_admin_action_audit_target'), table_name='admin_action_audit')
    op.drop_index(op.f('ix_admin_action_audit_id'), table_name='admin_action_audit')
    op.drop_index(op.f('ix_admin_action_audit_created_at'), table_name='admin_action_audit')
    op.drop_index(op.f('ix_admin_action_audit_admin_user_id'), table_name='admin_action_audit')
    op.drop_index(op.f('ix_admin_action_audit_action_type'), table_name='admin_action_audit')
    op.drop_table('admin_action_audit')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_index(op.f('ix_users_kyc_verified'), table_name='users')
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_seasons_name'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_processed_events_id'), table_name='processed_events')
    op.drop_index(op.f('ix_processed_events_event_type'), table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_poll_ingest_state_last_ingested_at'), table_name='poll_ingest_state')
    op.drop_index(op.f('ix_poll_ingest_state_last_ack_event_id'), table_name='poll_ingest_state')
    op.drop_index(op.f('ix_poll_ingest_state_id'), table_name='poll_ingest_state')
    op.drop_table('poll_ingest_state')
    op.drop_index(op.f('ix_merkle_snapshots_merkle_root'), table_name='merkle_snapshots')
    op.drop_index(op.f('ix_merkle_snapshots_last_event_id'), table_name='merkle_snapshots')
    op.drop_index(op.f('ix_merkle_snapshots_id'), table_name='merkle_snapshots')
    op.drop_index(op.f('ix_merkle_snapshots_created_at'), table_name='merkle_snapshots')
    op.drop_index(op.f('ix_merkle_snapshots_anchor_tx_hash'), table_name='merkle_snapshots')
    op.drop_table('merkle_snapshots')
    op.drop_index(op.f('ix_merkle_accumulator_updated_at'), table_name='merkle_accumulator')
    op.drop_index(op.f('ix_merkle_accumulator_level'), table_name='merkle_accumulator')
    op.drop_index(op.f('ix_merkle_accumulator_id'), table_name='merkle_accumulator')
    op.drop_table('merkle_accumulator')
    op.drop_index(op.f('ix_marketplace_order_cache_token_id'), table_name='marketplace_order_cache')
    op.drop_index(op.f('ix_marketplace_order_cache_seller_wallet'), table_name='marketplace_order_cache')
    op.drop_index(op.f('ix_marketplace_order_cache_order_id'), table_name='marketplace_order_cache')
    op.drop_index(op.f('ix_marketplace_order_cache_fulfilled_tx_hash'), table_name='marketplace_order_cache')
    op.drop_index(op.f('ix_marketplace_order_cache_fulfilled_block_time'), table_name='marketplace_order_cache')
    op.drop_index(op.f('ix_marketplace_order_cache_domain_contract'), table_name='marketplace_order_cache')
    op.drop_index(op.f('ix_marketplace_order_cache_created_block_time'), table_name='marketplace_order_cache')
    op.drop_index(op.f('ix_marketplace_order_cache_created_at'), table_name='marketplace_order_cache')
    op.drop_table('marketplace_order_cache')
    op.drop_index(op.f('ix_idempotency_keys_route'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_created_at'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_governance_config_updated_at'), table_name='governance_config')
    op.drop_index(op.f('ix_governance_config_key'), table_name='governance_config')
    op.drop_index(op.f('ix_governance_config_id'), table_name='governance_config')
    op.drop_table('governance_config')
    op.drop_index(op.f('ix_domains_tld'), table_name='domains')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_index(op.f('ix_domains_last_orderbook_snapshot_at'), table_name='domains')
    op.drop_index(op.f('ix_domains_id'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_domain_whitelist_id'), table_name='domain_whitelist')
    op.drop_index(op.f('ix_domain_whitelist_domain_name'), table_name='domain_whitelist')
    op.drop_index(op.f('ix_domain_whitelist_active'), table_name='domain_whitelist')
    op.drop_table('domain_whitelist')
    # ### end Alembic commands ###
