"""increase_price_precision_for_wei_values

Revision ID: 3973557be748
Revises: cb3d70ec1058
Create Date: 2025-10-02 11:12:54.319668

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3973557be748'
down_revision = 'cb3d70ec1058'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chain_ingest_state')
    op.alter_column('domain_listings', 'price',
               existing_type=sa.NUMERIC(precision=24, scale=8),
               type_=sa.Numeric(precision=30, scale=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('domain_listings', 'price',
               existing_type=sa.Numeric(precision=30, scale=8),
               type_=sa.NUMERIC(precision=24, scale=8),
               existing_nullable=False)
    op.create_table('chain_ingest_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_block', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_hash', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chain_ingest_state_pkey'))
    )
    # ### end Alembic commands ###
