"""new schema

Revision ID: 47e680f70874
Revises: 
Create Date: 2025-09-04 16:16:33.128785

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '47e680f70874'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_whitelist_active'), 'domain_whitelist', ['active'], unique=False)
    op.create_index(op.f('ix_domain_whitelist_domain_name'), 'domain_whitelist', ['domain_name'], unique=True)
    op.create_index(op.f('ix_domain_whitelist_id'), 'domain_whitelist', ['id'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tld', sa.String(length=32), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_floor_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('last_estimated_value', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('last_orderbook_snapshot_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_id'), 'domains', ['id'], unique=False)
    op.create_index(op.f('ix_domains_last_orderbook_snapshot_at'), 'domains', ['last_orderbook_snapshot_at'], unique=False)
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=True)
    op.create_index(op.f('ix_domains_tld'), 'domains', ['tld'], unique=False)
    op.create_table('processed_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id', name='uq_processed_events_unique')
    )
    op.create_index(op.f('ix_processed_events_id'), 'processed_events', ['id'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_id'), 'seasons', ['id'], unique=False)
    op.create_index(op.f('ix_seasons_name'), 'seasons', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_address', sa.String(length=42), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_fee', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitions_contract_address'), 'competitions', ['contract_address'], unique=True)
    op.create_index(op.f('ix_competitions_id'), 'competitions', ['id'], unique=False)
    op.create_index(op.f('ix_competitions_season_id'), 'competitions', ['season_id'], unique=False)
    op.create_table('domain_valuation_disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_valuation_disputes_created_at'), 'domain_valuation_disputes', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_valuation_disputes_created_by_user_id'), 'domain_valuation_disputes', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_domain_valuation_disputes_domain_name'), 'domain_valuation_disputes', ['domain_name'], unique=False)
    op.create_index(op.f('ix_domain_valuation_disputes_id'), 'domain_valuation_disputes', ['id'], unique=False)
    op.create_index(op.f('ix_domain_valuation_disputes_resolved_at'), 'domain_valuation_disputes', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_domain_valuation_disputes_status'), 'domain_valuation_disputes', ['status'], unique=False)
    op.create_table('domain_valuation_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('override_value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_name', name='uq_domain_override_domain')
    )
    op.create_index(op.f('ix_domain_valuation_overrides_created_at'), 'domain_valuation_overrides', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_valuation_overrides_created_by_user_id'), 'domain_valuation_overrides', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_domain_valuation_overrides_domain_name'), 'domain_valuation_overrides', ['domain_name'], unique=False)
    op.create_index(op.f('ix_domain_valuation_overrides_expires_at'), 'domain_valuation_overrides', ['expires_at'], unique=False)
    op.create_index(op.f('ix_domain_valuation_overrides_id'), 'domain_valuation_overrides', ['id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('seller_wallet', sa.String(length=42), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('external_order_id', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_index(op.f('ix_listings_active'), 'listings', ['active'], unique=False)
    op.create_index(op.f('ix_listings_domain_name'), 'listings', ['domain_name'], unique=False)
    op.create_index(op.f('ix_listings_expires_at'), 'listings', ['expires_at'], unique=False)
    op.create_index(op.f('ix_listings_external_order_id'), 'listings', ['external_order_id'], unique=True)
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    op.create_index(op.f('ix_listings_seller_wallet'), 'listings', ['seller_wallet'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('buyer_wallet', sa.String(length=42), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('external_order_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_index(op.f('ix_offers_active'), 'offers', ['active'], unique=False)
    op.create_index(op.f('ix_offers_buyer_wallet'), 'offers', ['buyer_wallet'], unique=False)
    op.create_index(op.f('ix_offers_domain_name'), 'offers', ['domain_name'], unique=False)
    op.create_index(op.f('ix_offers_external_order_id'), 'offers', ['external_order_id'], unique=True)
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_table('orderbook_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('size', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderbook_snapshots_collected_at'), 'orderbook_snapshots', ['collected_at'], unique=False)
    op.create_index(op.f('ix_orderbook_snapshots_domain_name'), 'orderbook_snapshots', ['domain_name'], unique=False)
    op.create_index(op.f('ix_orderbook_snapshots_id'), 'orderbook_snapshots', ['id'], unique=False)
    op.create_table('valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuations_created_at'), 'valuations', ['created_at'], unique=False)
    op.create_index(op.f('ix_valuations_domain_name'), 'valuations', ['domain_name'], unique=False)
    op.create_index(op.f('ix_valuations_id'), 'valuations', ['id'], unique=False)
    op.create_table('competition_epochs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('epoch_index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reward_pool', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('distributed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'epoch_index', name='uq_competition_epoch_idx')
    )
    op.create_index(op.f('ix_competition_epochs_competition_id'), 'competition_epochs', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_epochs_distributed'), 'competition_epochs', ['distributed'], unique=False)
    op.create_index(op.f('ix_competition_epochs_id'), 'competition_epochs', ['id'], unique=False)
    op.create_table('domain_etfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_shares', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('nav_last', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('nav_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creation_unit_size', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('management_fee_bps', sa.Integer(), nullable=True),
    sa.Column('performance_fee_bps', sa.Integer(), nullable=True),
    sa.Column('fee_accrued', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', name='uq_domain_etf_symbol')
    )
    op.create_index(op.f('ix_domain_etfs_competition_id'), 'domain_etfs', ['competition_id'], unique=False)
    op.create_index(op.f('ix_domain_etfs_id'), 'domain_etfs', ['id'], unique=False)
    op.create_index(op.f('ix_domain_etfs_owner_user_id'), 'domain_etfs', ['owner_user_id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_table('competition_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('epoch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('sharpe_like', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('turnover_ratio', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('concentration_index', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('reward_amount', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('distributed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['epoch_id'], ['competition_epochs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('epoch_id', 'user_id', name='uq_epoch_user_reward')
    )
    op.create_index(op.f('ix_competition_rewards_competition_id'), 'competition_rewards', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_rewards_distributed_at'), 'competition_rewards', ['distributed_at'], unique=False)
    op.create_index(op.f('ix_competition_rewards_epoch_id'), 'competition_rewards', ['epoch_id'], unique=False)
    op.create_index(op.f('ix_competition_rewards_id'), 'competition_rewards', ['id'], unique=False)
    op.create_index(op.f('ix_competition_rewards_user_id'), 'competition_rewards', ['user_id'], unique=False)
    op.create_table('domain_etf_nav_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nav_per_share', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['etf_id'], ['domain_etfs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_etf_nav_history_etf_id'), 'domain_etf_nav_history', ['etf_id'], unique=False)
    op.create_index(op.f('ix_domain_etf_nav_history_id'), 'domain_etf_nav_history', ['id'], unique=False)
    op.create_index(op.f('ix_domain_etf_nav_history_snapshot_time'), 'domain_etf_nav_history', ['snapshot_time'], unique=False)
    op.create_table('domain_etf_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('weight_bps', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.ForeignKeyConstraint(['etf_id'], ['domain_etfs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etf_id', 'domain_name', name='uq_domain_etf_domain')
    )
    op.create_index(op.f('ix_domain_etf_positions_domain_name'), 'domain_etf_positions', ['domain_name'], unique=False)
    op.create_index(op.f('ix_domain_etf_positions_etf_id'), 'domain_etf_positions', ['etf_id'], unique=False)
    op.create_index(op.f('ix_domain_etf_positions_id'), 'domain_etf_positions', ['id'], unique=False)
    op.create_table('domain_etf_redemption_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('nav_per_share_snapshot', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['etf_id'], ['domain_etfs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_etf_redemption_intents_created_at'), 'domain_etf_redemption_intents', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_etf_redemption_intents_etf_id'), 'domain_etf_redemption_intents', ['etf_id'], unique=False)
    op.create_index(op.f('ix_domain_etf_redemption_intents_executed_at'), 'domain_etf_redemption_intents', ['executed_at'], unique=False)
    op.create_index(op.f('ix_domain_etf_redemption_intents_id'), 'domain_etf_redemption_intents', ['id'], unique=False)
    op.create_index(op.f('ix_domain_etf_redemption_intents_user_id'), 'domain_etf_redemption_intents', ['user_id'], unique=False)
    op.create_table('domain_etf_share_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flow_type', sa.String(length=8), nullable=False),
    sa.Column('shares', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('cash_value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('nav_per_share', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('settlement_order_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['etf_id'], ['domain_etfs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_etf_share_flows_created_at'), 'domain_etf_share_flows', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_etf_share_flows_etf_id'), 'domain_etf_share_flows', ['etf_id'], unique=False)
    op.create_index(op.f('ix_domain_etf_share_flows_id'), 'domain_etf_share_flows', ['id'], unique=False)
    op.create_index(op.f('ix_domain_etf_share_flows_user_id'), 'domain_etf_share_flows', ['user_id'], unique=False)
    op.create_table('domain_etf_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('lock_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['etf_id'], ['domain_etfs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etf_id', 'user_id', name='uq_domain_etf_share_holder')
    )
    op.create_index(op.f('ix_domain_etf_shares_etf_id'), 'domain_etf_shares', ['etf_id'], unique=False)
    op.create_index(op.f('ix_domain_etf_shares_id'), 'domain_etf_shares', ['id'], unique=False)
    op.create_index(op.f('ix_domain_etf_shares_lock_until'), 'domain_etf_shares', ['lock_until'], unique=False)
    op.create_index(op.f('ix_domain_etf_shares_user_id'), 'domain_etf_shares', ['user_id'], unique=False)
    op.create_table('participant_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'domain_name', name='uq_participant_domain_holding')
    )
    op.create_index(op.f('ix_participant_holdings_domain_name'), 'participant_holdings', ['domain_name'], unique=False)
    op.create_index(op.f('ix_participant_holdings_id'), 'participant_holdings', ['id'], unique=False)
    op.create_index(op.f('ix_participant_holdings_participant_id'), 'participant_holdings', ['participant_id'], unique=False)
    op.create_index(op.f('ix_participant_holdings_updated_at'), 'participant_holdings', ['updated_at'], unique=False)
    op.create_table('portfolio_value_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_value_history_id'), 'portfolio_value_history', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_value_history_participant_id'), 'portfolio_value_history', ['participant_id'], unique=False)
    op.create_index(op.f('ix_portfolio_value_history_snapshot_time'), 'portfolio_value_history', ['snapshot_time'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('domain_token_address', sa.String(length=42), nullable=False),
    sa.Column('domain_token_id', sa.String(length=255), nullable=False),
    sa.Column('trade_type', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_tx_hash'), 'trades', ['tx_hash'], unique=False)
    op.create_table('trade_risk_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_risk_flags_created_at'), 'trade_risk_flags', ['created_at'], unique=False)
    op.create_index(op.f('ix_trade_risk_flags_flag_type'), 'trade_risk_flags', ['flag_type'], unique=False)
    op.create_index(op.f('ix_trade_risk_flags_id'), 'trade_risk_flags', ['id'], unique=False)
    op.create_index(op.f('ix_trade_risk_flags_trade_id'), 'trade_risk_flags', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_risk_flags_trade_id'), table_name='trade_risk_flags')
    op.drop_index(op.f('ix_trade_risk_flags_id'), table_name='trade_risk_flags')
    op.drop_index(op.f('ix_trade_risk_flags_flag_type'), table_name='trade_risk_flags')
    op.drop_index(op.f('ix_trade_risk_flags_created_at'), table_name='trade_risk_flags')
    op.drop_table('trade_risk_flags')
    op.drop_index(op.f('ix_trades_tx_hash'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_portfolio_value_history_snapshot_time'), table_name='portfolio_value_history')
    op.drop_index(op.f('ix_portfolio_value_history_participant_id'), table_name='portfolio_value_history')
    op.drop_index(op.f('ix_portfolio_value_history_id'), table_name='portfolio_value_history')
    op.drop_table('portfolio_value_history')
    op.drop_index(op.f('ix_participant_holdings_updated_at'), table_name='participant_holdings')
    op.drop_index(op.f('ix_participant_holdings_participant_id'), table_name='participant_holdings')
    op.drop_index(op.f('ix_participant_holdings_id'), table_name='participant_holdings')
    op.drop_index(op.f('ix_participant_holdings_domain_name'), table_name='participant_holdings')
    op.drop_table('participant_holdings')
    op.drop_index(op.f('ix_domain_etf_shares_user_id'), table_name='domain_etf_shares')
    op.drop_index(op.f('ix_domain_etf_shares_lock_until'), table_name='domain_etf_shares')
    op.drop_index(op.f('ix_domain_etf_shares_id'), table_name='domain_etf_shares')
    op.drop_index(op.f('ix_domain_etf_shares_etf_id'), table_name='domain_etf_shares')
    op.drop_table('domain_etf_shares')
    op.drop_index(op.f('ix_domain_etf_share_flows_user_id'), table_name='domain_etf_share_flows')
    op.drop_index(op.f('ix_domain_etf_share_flows_id'), table_name='domain_etf_share_flows')
    op.drop_index(op.f('ix_domain_etf_share_flows_etf_id'), table_name='domain_etf_share_flows')
    op.drop_index(op.f('ix_domain_etf_share_flows_created_at'), table_name='domain_etf_share_flows')
    op.drop_table('domain_etf_share_flows')
    op.drop_index(op.f('ix_domain_etf_redemption_intents_user_id'), table_name='domain_etf_redemption_intents')
    op.drop_index(op.f('ix_domain_etf_redemption_intents_id'), table_name='domain_etf_redemption_intents')
    op.drop_index(op.f('ix_domain_etf_redemption_intents_executed_at'), table_name='domain_etf_redemption_intents')
    op.drop_index(op.f('ix_domain_etf_redemption_intents_etf_id'), table_name='domain_etf_redemption_intents')
    op.drop_index(op.f('ix_domain_etf_redemption_intents_created_at'), table_name='domain_etf_redemption_intents')
    op.drop_table('domain_etf_redemption_intents')
    op.drop_index(op.f('ix_domain_etf_positions_id'), table_name='domain_etf_positions')
    op.drop_index(op.f('ix_domain_etf_positions_etf_id'), table_name='domain_etf_positions')
    op.drop_index(op.f('ix_domain_etf_positions_domain_name'), table_name='domain_etf_positions')
    op.drop_table('domain_etf_positions')
    op.drop_index(op.f('ix_domain_etf_nav_history_snapshot_time'), table_name='domain_etf_nav_history')
    op.drop_index(op.f('ix_domain_etf_nav_history_id'), table_name='domain_etf_nav_history')
    op.drop_index(op.f('ix_domain_etf_nav_history_etf_id'), table_name='domain_etf_nav_history')
    op.drop_table('domain_etf_nav_history')
    op.drop_index(op.f('ix_competition_rewards_user_id'), table_name='competition_rewards')
    op.drop_index(op.f('ix_competition_rewards_id'), table_name='competition_rewards')
    op.drop_index(op.f('ix_competition_rewards_epoch_id'), table_name='competition_rewards')
    op.drop_index(op.f('ix_competition_rewards_distributed_at'), table_name='competition_rewards')
    op.drop_index(op.f('ix_competition_rewards_competition_id'), table_name='competition_rewards')
    op.drop_table('competition_rewards')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_domain_etfs_owner_user_id'), table_name='domain_etfs')
    op.drop_index(op.f('ix_domain_etfs_id'), table_name='domain_etfs')
    op.drop_index(op.f('ix_domain_etfs_competition_id'), table_name='domain_etfs')
    op.drop_table('domain_etfs')
    op.drop_index(op.f('ix_competition_epochs_id'), table_name='competition_epochs')
    op.drop_index(op.f('ix_competition_epochs_distributed'), table_name='competition_epochs')
    op.drop_index(op.f('ix_competition_epochs_competition_id'), table_name='competition_epochs')
    op.drop_table('competition_epochs')
    op.drop_index(op.f('ix_valuations_id'), table_name='valuations')
    op.drop_index(op.f('ix_valuations_domain_name'), table_name='valuations')
    op.drop_index(op.f('ix_valuations_created_at'), table_name='valuations')
    op.drop_table('valuations')
    op.drop_index(op.f('ix_orderbook_snapshots_id'), table_name='orderbook_snapshots')
    op.drop_index(op.f('ix_orderbook_snapshots_domain_name'), table_name='orderbook_snapshots')
    op.drop_index(op.f('ix_orderbook_snapshots_collected_at'), table_name='orderbook_snapshots')
    op.drop_table('orderbook_snapshots')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_external_order_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_domain_name'), table_name='offers')
    op.drop_index(op.f('ix_offers_buyer_wallet'), table_name='offers')
    op.drop_index(op.f('ix_offers_active'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_listings_seller_wallet'), table_name='listings')
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_external_order_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_expires_at'), table_name='listings')
    op.drop_index(op.f('ix_listings_domain_name'), table_name='listings')
    op.drop_index(op.f('ix_listings_active'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_domain_valuation_overrides_id'), table_name='domain_valuation_overrides')
    op.drop_index(op.f('ix_domain_valuation_overrides_expires_at'), table_name='domain_valuation_overrides')
    op.drop_index(op.f('ix_domain_valuation_overrides_domain_name'), table_name='domain_valuation_overrides')
    op.drop_index(op.f('ix_domain_valuation_overrides_created_by_user_id'), table_name='domain_valuation_overrides')
    op.drop_index(op.f('ix_domain_valuation_overrides_created_at'), table_name='domain_valuation_overrides')
    op.drop_table('domain_valuation_overrides')
    op.drop_index(op.f('ix_domain_valuation_disputes_status'), table_name='domain_valuation_disputes')
    op.drop_index(op.f('ix_domain_valuation_disputes_resolved_at'), table_name='domain_valuation_disputes')
    op.drop_index(op.f('ix_domain_valuation_disputes_id'), table_name='domain_valuation_disputes')
    op.drop_index(op.f('ix_domain_valuation_disputes_domain_name'), table_name='domain_valuation_disputes')
    op.drop_index(op.f('ix_domain_valuation_disputes_created_by_user_id'), table_name='domain_valuation_disputes')
    op.drop_index(op.f('ix_domain_valuation_disputes_created_at'), table_name='domain_valuation_disputes')
    op.drop_table('domain_valuation_disputes')
    op.drop_index(op.f('ix_competitions_season_id'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_id'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_contract_address'), table_name='competitions')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_seasons_name'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_processed_events_id'), table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_domains_tld'), table_name='domains')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_index(op.f('ix_domains_last_orderbook_snapshot_at'), table_name='domains')
    op.drop_index(op.f('ix_domains_id'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_domain_whitelist_id'), table_name='domain_whitelist')
    op.drop_index(op.f('ix_domain_whitelist_domain_name'), table_name='domain_whitelist')
    op.drop_index(op.f('ix_domain_whitelist_active'), table_name='domain_whitelist')
    op.drop_table('domain_whitelist')
    # ### end Alembic commands ###
