"""updating the schemas to have merkle accumulator

Revision ID: 5a763721a9ec
Revises: ff95c34bba34
Create Date: 2025-09-04 18:38:49.028108

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5a763721a9ec'
down_revision = 'ff95c34bba34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merkle_accumulator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('node_hash', sa.String(length=66), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merkle_accumulator_id'), 'merkle_accumulator', ['id'], unique=False)
    op.create_index(op.f('ix_merkle_accumulator_level'), 'merkle_accumulator', ['level'], unique=True)
    op.create_index(op.f('ix_merkle_accumulator_updated_at'), 'merkle_accumulator', ['updated_at'], unique=False)
    op.add_column('merkle_snapshots', sa.Column('signature', sa.String(length=512), nullable=True))
    op.add_column('merkle_snapshots', sa.Column('anchor_tx_hash', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_merkle_snapshots_anchor_tx_hash'), 'merkle_snapshots', ['anchor_tx_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merkle_snapshots_anchor_tx_hash'), table_name='merkle_snapshots')
    op.drop_column('merkle_snapshots', 'anchor_tx_hash')
    op.drop_column('merkle_snapshots', 'signature')
    op.drop_index(op.f('ix_merkle_accumulator_updated_at'), table_name='merkle_accumulator')
    op.drop_index(op.f('ix_merkle_accumulator_level'), table_name='merkle_accumulator')
    op.drop_index(op.f('ix_merkle_accumulator_id'), table_name='merkle_accumulator')
    op.drop_table('merkle_accumulator')
    # ### end Alembic commands ###
