"""Added domarank score and fractionalization

Revision ID: 7283b3547840
Revises: a40877827d5e
Create Date: 2025-10-08 10:23:59.445232

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7283b3547840'
down_revision = 'a40877827d5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('doma_rank_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('age_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('demand_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('keyword_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('market_price_usd', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('oracle_price_usd', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('confidence_level', sa.String(length=16), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_valuations_calculated_at'), 'domain_valuations', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_domain_valuations_confidence_level'), 'domain_valuations', ['confidence_level'], unique=False)
    op.create_index(op.f('ix_domain_valuations_domain_name'), 'domain_valuations', ['domain_name'], unique=False)
    op.create_index(op.f('ix_domain_valuations_id'), 'domain_valuations', ['id'], unique=False)
    op.create_table('fractional_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_address', sa.String(length=42), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('total_supply', sa.Numeric(precision=30, scale=0), nullable=False),
    sa.Column('current_price_usd', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('fractionalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('minimum_buyout_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('is_bought_out', sa.Boolean(), nullable=True),
    sa.Column('buyout_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('buyout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('twitter_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['domain_name'], ['domains.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fractional_tokens_domain_name'), 'fractional_tokens', ['domain_name'], unique=False)
    op.create_index(op.f('ix_fractional_tokens_id'), 'fractional_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_fractional_tokens_is_bought_out'), 'fractional_tokens', ['is_bought_out'], unique=False)
    op.create_index(op.f('ix_fractional_tokens_token_address'), 'fractional_tokens', ['token_address'], unique=True)
    op.drop_table('chain_ingest_state')
    op.add_column('domains', sa.Column('doma_rank_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('domains', sa.Column('is_fractionalized', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_domains_doma_rank_score'), 'domains', ['doma_rank_score'], unique=False)
    op.create_index(op.f('ix_domains_is_fractionalized'), 'domains', ['is_fractionalized'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domains_is_fractionalized'), table_name='domains')
    op.drop_index(op.f('ix_domains_doma_rank_score'), table_name='domains')
    op.drop_column('domains', 'is_fractionalized')
    op.drop_column('domains', 'doma_rank_score')
    op.create_table('chain_ingest_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_block', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_hash', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chain_ingest_state_pkey'))
    )
    op.drop_index(op.f('ix_fractional_tokens_token_address'), table_name='fractional_tokens')
    op.drop_index(op.f('ix_fractional_tokens_is_bought_out'), table_name='fractional_tokens')
    op.drop_index(op.f('ix_fractional_tokens_id'), table_name='fractional_tokens')
    op.drop_index(op.f('ix_fractional_tokens_domain_name'), table_name='fractional_tokens')
    op.drop_table('fractional_tokens')
    op.drop_index(op.f('ix_domain_valuations_id'), table_name='domain_valuations')
    op.drop_index(op.f('ix_domain_valuations_domain_name'), table_name='domain_valuations')
    op.drop_index(op.f('ix_domain_valuations_confidence_level'), table_name='domain_valuations')
    op.drop_index(op.f('ix_domain_valuations_calculated_at'), table_name='domain_valuations')
    op.drop_table('domain_valuations')
    # ### end Alembic commands ###
