"""add chain ingestion

Revision ID: 84eb47006f37
Revises: 2754af72a70b
Create Date: 2025-09-04 21:57:24.280682

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '84eb47006f37'
down_revision = '2754af72a70b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chain_ingest_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain_ingest_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_block', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_hash', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chain_ingest_state_pkey'))
    )
    # ### end Alembic commands ###
