"""updating the schemas to revamp the merkle accumulator

Revision ID: 8e344496d510
Revises: 5a763721a9ec
Create Date: 2025-09-04 19:27:54.786251

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8e344496d510'
down_revision = '5a763721a9ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
