"""addraw reward amount

Revision ID: 98303b7746fc
Revises: e4129e16e58e
Create Date: 2025-09-06 09:13:37.875867

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '98303b7746fc'
down_revision = 'e4129e16e58e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chain_ingest_state')
    op.add_column('competition_rewards', sa.Column('raw_reward_amount', sa.Numeric(precision=24, scale=8), nullable=True))
    op.add_column('competition_rewards', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_competition_rewards_claimed_at'), 'competition_rewards', ['claimed_at'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('kyc_verified', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    op.create_index(op.f('ix_users_kyc_verified'), 'users', ['kyc_verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_kyc_verified'), table_name='users')
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_column('users', 'kyc_verified')
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_competition_rewards_claimed_at'), table_name='competition_rewards')
    op.drop_column('competition_rewards', 'claimed_at')
    op.drop_column('competition_rewards', 'raw_reward_amount')
    op.create_table('chain_ingest_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_block', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_hash', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chain_ingest_state_pkey'))
    )
    # ### end Alembic commands ###
