"""alter marketplace transactions price type

Revision ID: a40877827d5e
Revises: 3973557be748
Create Date: 2025-10-02 13:05:00.951772

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a40877827d5e'
down_revision = '3973557be748'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chain_ingest_state')
    op.alter_column('marketplace_transactions', 'price',
               existing_type=sa.NUMERIC(precision=24, scale=8),
               type_=sa.Numeric(precision=30, scale=8),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketplace_transactions', 'price',
               existing_type=sa.Numeric(precision=30, scale=8),
               type_=sa.NUMERIC(precision=24, scale=8),
               existing_nullable=True)
    op.create_table('chain_ingest_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_block', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_hash', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chain_ingest_state_pkey'))
    )
    # ### end Alembic commands ###
