"""updating the schemas to add integrity hash column

Revision ID: aad32567bf88
Revises: 8e344496d510
Create Date: 2025-09-04 19:45:56.019005

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'aad32567bf88'
down_revision = '8e344496d510'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('integrity_hash', sa.String(length=130), nullable=True))
    op.create_index(op.f('ix_audit_events_integrity_hash'), 'audit_events', ['integrity_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_integrity_hash'), table_name='audit_events')
    op.drop_column('audit_events', 'integrity_hash')
    # ### end Alembic commands ###
