"""add new models

Revision ID: cb3d70ec1058
Revises: 7a9230717ddb
Create Date: 2025-10-01 19:18:35.838454

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cb3d70ec1058'
down_revision = '7a9230717ddb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('futures_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.String(length=255), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('size', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('margin', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('leverage', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('liquidation_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('chain_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_futures_positions_chain_id'), 'futures_positions', ['chain_id'], unique=False)
    op.create_index(op.f('ix_futures_positions_closed_at'), 'futures_positions', ['closed_at'], unique=False)
    op.create_index(op.f('ix_futures_positions_contract_id'), 'futures_positions', ['contract_id'], unique=False)
    op.create_index(op.f('ix_futures_positions_domain_name'), 'futures_positions', ['domain_name'], unique=False)
    op.create_index(op.f('ix_futures_positions_id'), 'futures_positions', ['id'], unique=False)
    op.create_index(op.f('ix_futures_positions_opened_at'), 'futures_positions', ['opened_at'], unique=False)
    op.create_index(op.f('ix_futures_positions_side'), 'futures_positions', ['side'], unique=False)
    op.create_index(op.f('ix_futures_positions_status'), 'futures_positions', ['status'], unique=False)
    op.create_index(op.f('ix_futures_positions_user_id'), 'futures_positions', ['user_id'], unique=False)
    op.create_table('marketplace_transactions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('contract_address', sa.String(length=42), nullable=False),
    sa.Column('token_id', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('chain_id', sa.String(length=32), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('gas_used', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('gas_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('marketplace_fee', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_transactions_chain_id'), 'marketplace_transactions', ['chain_id'], unique=False)
    op.create_index(op.f('ix_marketplace_transactions_confirmed_at'), 'marketplace_transactions', ['confirmed_at'], unique=False)
    op.create_index(op.f('ix_marketplace_transactions_contract_address'), 'marketplace_transactions', ['contract_address'], unique=False)
    op.create_index(op.f('ix_marketplace_transactions_created_at'), 'marketplace_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_marketplace_transactions_id'), 'marketplace_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_transactions_order_id'), 'marketplace_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_marketplace_transactions_status'), 'marketplace_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_marketplace_transactions_token_id'), 'marketplace_transactions', ['token_id'], unique=False)
    op.create_index(op.f('ix_marketplace_transactions_transaction_type'), 'marketplace_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_marketplace_transactions_tx_hash'), 'marketplace_transactions', ['tx_hash'], unique=False)
    op.create_index(op.f('ix_marketplace_transactions_user_id'), 'marketplace_transactions', ['user_id'], unique=False)
    op.create_table('collateral_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain_contract', sa.String(length=42), nullable=False),
    sa.Column('token_id', sa.String(length=255), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=True),
    sa.Column('collateral_value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('borrowed_amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('health_factor', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('liquidation_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('chain_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('acquisition_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['acquisition_transaction_id'], ['marketplace_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collateral_positions_chain_id'), 'collateral_positions', ['chain_id'], unique=False)
    op.create_index(op.f('ix_collateral_positions_created_at'), 'collateral_positions', ['created_at'], unique=False)
    op.create_index(op.f('ix_collateral_positions_domain_contract'), 'collateral_positions', ['domain_contract'], unique=False)
    op.create_index(op.f('ix_collateral_positions_domain_name'), 'collateral_positions', ['domain_name'], unique=False)
    op.create_index(op.f('ix_collateral_positions_id'), 'collateral_positions', ['id'], unique=False)
    op.create_index(op.f('ix_collateral_positions_status'), 'collateral_positions', ['status'], unique=False)
    op.create_index(op.f('ix_collateral_positions_token_id'), 'collateral_positions', ['token_id'], unique=False)
    op.create_index(op.f('ix_collateral_positions_user_id'), 'collateral_positions', ['user_id'], unique=False)
    op.create_table('domain_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contract_address', sa.String(length=42), nullable=False),
    sa.Column('token_id', sa.String(length=255), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('chain_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expiration_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marketplace_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_transaction_id'], ['marketplace_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_listings_chain_id'), 'domain_listings', ['chain_id'], unique=False)
    op.create_index(op.f('ix_domain_listings_contract_address'), 'domain_listings', ['contract_address'], unique=False)
    op.create_index(op.f('ix_domain_listings_created_at'), 'domain_listings', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_listings_domain_name'), 'domain_listings', ['domain_name'], unique=False)
    op.create_index(op.f('ix_domain_listings_expiration_time'), 'domain_listings', ['expiration_time'], unique=False)
    op.create_index(op.f('ix_domain_listings_id'), 'domain_listings', ['id'], unique=False)
    op.create_index(op.f('ix_domain_listings_order_id'), 'domain_listings', ['order_id'], unique=True)
    op.create_index(op.f('ix_domain_listings_status'), 'domain_listings', ['status'], unique=False)
    op.create_index(op.f('ix_domain_listings_token_id'), 'domain_listings', ['token_id'], unique=False)
    op.create_index(op.f('ix_domain_listings_user_id'), 'domain_listings', ['user_id'], unique=False)
    op.create_table('domain_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contract_address', sa.String(length=42), nullable=False),
    sa.Column('token_id', sa.String(length=255), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('chain_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expiration_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('marketplace_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_transaction_id'], ['marketplace_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_offers_chain_id'), 'domain_offers', ['chain_id'], unique=False)
    op.create_index(op.f('ix_domain_offers_contract_address'), 'domain_offers', ['contract_address'], unique=False)
    op.create_index(op.f('ix_domain_offers_created_at'), 'domain_offers', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_offers_domain_name'), 'domain_offers', ['domain_name'], unique=False)
    op.create_index(op.f('ix_domain_offers_expiration_time'), 'domain_offers', ['expiration_time'], unique=False)
    op.create_index(op.f('ix_domain_offers_id'), 'domain_offers', ['id'], unique=False)
    op.create_index(op.f('ix_domain_offers_order_id'), 'domain_offers', ['order_id'], unique=True)
    op.create_index(op.f('ix_domain_offers_status'), 'domain_offers', ['status'], unique=False)
    op.create_index(op.f('ix_domain_offers_token_id'), 'domain_offers', ['token_id'], unique=False)
    op.create_index(op.f('ix_domain_offers_user_id'), 'domain_offers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_offers_user_id'), table_name='domain_offers')
    op.drop_index(op.f('ix_domain_offers_token_id'), table_name='domain_offers')
    op.drop_index(op.f('ix_domain_offers_status'), table_name='domain_offers')
    op.drop_index(op.f('ix_domain_offers_order_id'), table_name='domain_offers')
    op.drop_index(op.f('ix_domain_offers_id'), table_name='domain_offers')
    op.drop_index(op.f('ix_domain_offers_expiration_time'), table_name='domain_offers')
    op.drop_index(op.f('ix_domain_offers_domain_name'), table_name='domain_offers')
    op.drop_index(op.f('ix_domain_offers_created_at'), table_name='domain_offers')
    op.drop_index(op.f('ix_domain_offers_contract_address'), table_name='domain_offers')
    op.drop_index(op.f('ix_domain_offers_chain_id'), table_name='domain_offers')
    op.drop_table('domain_offers')
    op.drop_index(op.f('ix_domain_listings_user_id'), table_name='domain_listings')
    op.drop_index(op.f('ix_domain_listings_token_id'), table_name='domain_listings')
    op.drop_index(op.f('ix_domain_listings_status'), table_name='domain_listings')
    op.drop_index(op.f('ix_domain_listings_order_id'), table_name='domain_listings')
    op.drop_index(op.f('ix_domain_listings_id'), table_name='domain_listings')
    op.drop_index(op.f('ix_domain_listings_expiration_time'), table_name='domain_listings')
    op.drop_index(op.f('ix_domain_listings_domain_name'), table_name='domain_listings')
    op.drop_index(op.f('ix_domain_listings_created_at'), table_name='domain_listings')
    op.drop_index(op.f('ix_domain_listings_contract_address'), table_name='domain_listings')
    op.drop_index(op.f('ix_domain_listings_chain_id'), table_name='domain_listings')
    op.drop_table('domain_listings')
    op.drop_index(op.f('ix_collateral_positions_user_id'), table_name='collateral_positions')
    op.drop_index(op.f('ix_collateral_positions_token_id'), table_name='collateral_positions')
    op.drop_index(op.f('ix_collateral_positions_status'), table_name='collateral_positions')
    op.drop_index(op.f('ix_collateral_positions_id'), table_name='collateral_positions')
    op.drop_index(op.f('ix_collateral_positions_domain_name'), table_name='collateral_positions')
    op.drop_index(op.f('ix_collateral_positions_domain_contract'), table_name='collateral_positions')
    op.drop_index(op.f('ix_collateral_positions_created_at'), table_name='collateral_positions')
    op.drop_index(op.f('ix_collateral_positions_chain_id'), table_name='collateral_positions')
    op.drop_table('collateral_positions')
    op.drop_index(op.f('ix_marketplace_transactions_user_id'), table_name='marketplace_transactions')
    op.drop_index(op.f('ix_marketplace_transactions_tx_hash'), table_name='marketplace_transactions')
    op.drop_index(op.f('ix_marketplace_transactions_transaction_type'), table_name='marketplace_transactions')
    op.drop_index(op.f('ix_marketplace_transactions_token_id'), table_name='marketplace_transactions')
    op.drop_index(op.f('ix_marketplace_transactions_status'), table_name='marketplace_transactions')
    op.drop_index(op.f('ix_marketplace_transactions_order_id'), table_name='marketplace_transactions')
    op.drop_index(op.f('ix_marketplace_transactions_id'), table_name='marketplace_transactions')
    op.drop_index(op.f('ix_marketplace_transactions_created_at'), table_name='marketplace_transactions')
    op.drop_index(op.f('ix_marketplace_transactions_contract_address'), table_name='marketplace_transactions')
    op.drop_index(op.f('ix_marketplace_transactions_confirmed_at'), table_name='marketplace_transactions')
    op.drop_index(op.f('ix_marketplace_transactions_chain_id'), table_name='marketplace_transactions')
    op.drop_table('marketplace_transactions')
    op.drop_index(op.f('ix_futures_positions_user_id'), table_name='futures_positions')
    op.drop_index(op.f('ix_futures_positions_status'), table_name='futures_positions')
    op.drop_index(op.f('ix_futures_positions_side'), table_name='futures_positions')
    op.drop_index(op.f('ix_futures_positions_opened_at'), table_name='futures_positions')
    op.drop_index(op.f('ix_futures_positions_id'), table_name='futures_positions')
    op.drop_index(op.f('ix_futures_positions_domain_name'), table_name='futures_positions')
    op.drop_index(op.f('ix_futures_positions_contract_id'), table_name='futures_positions')
    op.drop_index(op.f('ix_futures_positions_closed_at'), table_name='futures_positions')
    op.drop_index(op.f('ix_futures_positions_chain_id'), table_name='futures_positions')
    op.drop_table('futures_positions')
    # ### end Alembic commands ###
