"""for new json columns for volume tier thresholds and holding duration tiers

Revision ID: d2e0150e4eac
Revises: fc8b13fe445e
Create Date: 2025-09-06 00:28:00.028121

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd2e0150e4eac'
down_revision = 'fc8b13fe445e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chain_ingest_state')
    op.add_column('incentive_schedules', sa.Column('volume_tier_thresholds', sa.JSON(), nullable=True))
    op.add_column('incentive_schedules', sa.Column('holding_duration_tiers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incentive_schedules', 'holding_duration_tiers')
    op.drop_column('incentive_schedules', 'volume_tier_thresholds')
    op.create_table('chain_ingest_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_block', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_hash', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chain_ingest_state_pkey'))
    )
    # ### end Alembic commands ###
