"""updating the schemas for having etf economics

Revision ID: d5ad3eb1426f
Revises: f0e50d51c368
Create Date: 2025-09-04 16:30:46.503780

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd5ad3eb1426f'
down_revision = 'f0e50d51c368'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
