"""updating the schemas to add verify chain column

Revision ID: dd93e15ab88e
Revises: add_verified_onchain_redemption
Create Date: 2025-09-04 19:52:03.400991

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'dd93e15ab88e'
down_revision = 'add_verified_onchain_redemption'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
