"""added idempotency key table

Revision ID: e4129e16e58e
Revises: d2e0150e4eac
Create Date: 2025-09-06 00:39:58.684991

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e4129e16e58e'
down_revision = 'd2e0150e4eac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chain_ingest_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain_ingest_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_block', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_hash', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chain_ingest_state_pkey'))
    )
    # ### end Alembic commands ###
