"""updating the schemas for domains

Revision ID: f0e50d51c368
Revises: 47e680f70874
Create Date: 2025-09-04 16:24:27.698405

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f0e50d51c368'
down_revision = '47e680f70874'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_etf_fee_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('nav_per_share_snapshot', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['etf_id'], ['domain_etfs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_etf_fee_events_created_at'), 'domain_etf_fee_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_etf_fee_events_etf_id'), 'domain_etf_fee_events', ['etf_id'], unique=False)
    op.create_index(op.f('ix_domain_etf_fee_events_event_type'), 'domain_etf_fee_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_domain_etf_fee_events_id'), 'domain_etf_fee_events', ['id'], unique=False)
    op.create_table('domain_etf_revenue_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etf_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('fee_event_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['etf_id'], ['domain_etfs.id'], ),
    sa.ForeignKeyConstraint(['fee_event_id'], ['domain_etf_fee_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_etf_revenue_shares_created_at'), 'domain_etf_revenue_shares', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_etf_revenue_shares_etf_id'), 'domain_etf_revenue_shares', ['etf_id'], unique=False)
    op.create_index(op.f('ix_domain_etf_revenue_shares_fee_event_id'), 'domain_etf_revenue_shares', ['fee_event_id'], unique=False)
    op.create_index(op.f('ix_domain_etf_revenue_shares_id'), 'domain_etf_revenue_shares', ['id'], unique=False)
    op.create_index(op.f('ix_domain_etf_revenue_shares_user_id'), 'domain_etf_revenue_shares', ['user_id'], unique=False)
    op.add_column('domain_etfs', sa.Column('nav_high_water', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('domain_etfs', sa.Column('management_fee_last_accrued_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('domain_etfs', sa.Column('creation_fee_bps', sa.Integer(), nullable=True))
    op.add_column('domain_etfs', sa.Column('redemption_fee_bps', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_domain_etfs_management_fee_last_accrued_at'), 'domain_etfs', ['management_fee_last_accrued_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_etfs_management_fee_last_accrued_at'), table_name='domain_etfs')
    op.drop_column('domain_etfs', 'redemption_fee_bps')
    op.drop_column('domain_etfs', 'creation_fee_bps')
    op.drop_column('domain_etfs', 'management_fee_last_accrued_at')
    op.drop_column('domain_etfs', 'nav_high_water')
    op.drop_index(op.f('ix_domain_etf_revenue_shares_user_id'), table_name='domain_etf_revenue_shares')
    op.drop_index(op.f('ix_domain_etf_revenue_shares_id'), table_name='domain_etf_revenue_shares')
    op.drop_index(op.f('ix_domain_etf_revenue_shares_fee_event_id'), table_name='domain_etf_revenue_shares')
    op.drop_index(op.f('ix_domain_etf_revenue_shares_etf_id'), table_name='domain_etf_revenue_shares')
    op.drop_index(op.f('ix_domain_etf_revenue_shares_created_at'), table_name='domain_etf_revenue_shares')
    op.drop_table('domain_etf_revenue_shares')
    op.drop_index(op.f('ix_domain_etf_fee_events_id'), table_name='domain_etf_fee_events')
    op.drop_index(op.f('ix_domain_etf_fee_events_event_type'), table_name='domain_etf_fee_events')
    op.drop_index(op.f('ix_domain_etf_fee_events_etf_id'), table_name='domain_etf_fee_events')
    op.drop_index(op.f('ix_domain_etf_fee_events_created_at'), table_name='domain_etf_fee_events')
    op.drop_table('domain_etf_fee_events')
    # ### end Alembic commands ###
