"""added index to event type for processed events

Revision ID: f6d575bcf83e
Revises: d62ad435e6a1
Create Date: 2025-09-05 00:28:06.476045

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f6d575bcf83e'
down_revision = 'd62ad435e6a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_processed_events_event_type'), 'processed_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_events_event_type'), table_name='processed_events')
    # ### end Alembic commands ###
