"""updating the schemas to have audit events and merkle snapshot

Revision ID: ff95c34bba34
Revises: d5ad3eb1426f
Create Date: 2025-09-04 18:28:50.106851

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ff95c34bba34'
down_revision = 'd5ad3eb1426f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merkle_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_event_id', sa.Integer(), nullable=False),
    sa.Column('merkle_root', sa.String(length=66), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merkle_snapshots_created_at'), 'merkle_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_merkle_snapshots_id'), 'merkle_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_merkle_snapshots_last_event_id'), 'merkle_snapshots', ['last_event_id'], unique=False)
    op.create_index(op.f('ix_merkle_snapshots_merkle_root'), 'merkle_snapshots', ['merkle_root'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_merkle_snapshots_merkle_root'), table_name='merkle_snapshots')
    op.drop_index(op.f('ix_merkle_snapshots_last_event_id'), table_name='merkle_snapshots')
    op.drop_index(op.f('ix_merkle_snapshots_id'), table_name='merkle_snapshots')
    op.drop_index(op.f('ix_merkle_snapshots_created_at'), table_name='merkle_snapshots')
    op.drop_table('merkle_snapshots')
    # ### end Alembic commands ###
